---
- name: Install Jenkins
  hosts: all
  become: true

  vars:
    jenkins_url_repo: deb https://pkg.jenkins.io/debian-stable binary/
    jenkins_key: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    jenkins_user: "jenkins"
    jenkins_home: "/var/lib/jenkins"
    jenkins_admin_username: "jadmin"
    jenkins_admin_password: "admin"
    terraform_url: https://releases.hashicorp.com/terraform/1.0.2/terraform_1.0.2_linux_amd64.zip
    terraform_name_file: terraform_1.0.2_linux_amd64.zip


  tasks:
    - name: Update all apt packages
      retries: 5
      delay: 30
      register: result
      until: result is succeeded
      apt:
        update_cache=yes
        force_apt_get=yes
        cache_valid_time=3600

    - name: Install packages using apt
      retries: 5
      delay: 30
      register: result
      until: result is succeeded
      apt:
        name:
          - default-jdk
          - wget
          - ansible
          - unzip
        state: present
        update_cache: no

    - name: ensure the jenkins apt repository key is installed
      apt_key: url={{ jenkins_key }} state=present
      become: yes

    - name: ensure the repository is configured
      apt_repository: repo='{{ jenkins_url_repo }}' state=present
      become: yes

    - name: ensure jenkins is installed
      apt: name=jenkins update_cache=yes
      become: yes

    - name: ensure jenkins is running
      service: name=jenkins state=started enabled=yes

    - name: Terraform install
      command: wget {{ terraform_url }}

    - name: Unzip terraform
      command: unzip {{ terraform_name_file }}

    - name: Move terraform file to /usr/bin
      command: sudo mv -f terraform /usr/bin/

    - name: Set permission terraform
      file: path=/usr/bin/terraform mode=01777

    - name: Clone repository
      command: git clone https://github.com/fm1ck3y/DevOpsProject /tmp/DevOpsProject

    - name: Move jenkins files to /var/lib
      command: cp -r /tmp/DevOpsProject/Jenkins/jenkins /var/lib/

    - name: Set permission jobs in /var/lib/jenkins
      file: path=/var/lib/jenkins/jobs owner=jenkins group=jenkins mode=01777 state=directory recurse=yes

    - name: Set permission config file in /var/lib/jenkins
      file: path=/var/lib/jenkins/config.xml owner=jenkins group=jenkins mode=01777

    - name: Set permission AnsiColor file in /var/lib/jenkins
      file: path=/var/lib/jenkins/hudson.plugins.ansicolor.AnsiColorBuildWrapper.xml owner=jenkins group=jenkins mode=01777

    - name: Move terraform files to /opt/
      command: mv -f /tmp/DevOpsProject/FilesForJobs /opt/

    - name: Create inventory file in /opt/FilesForJobs/
      file: path=/opt/FilesForJobs/ state=touch owner=jenkins group=jenkins mode=01777

    - name: Init terraform
      command: terraform -chdir=/opt/FilesForJobs init

    - name: Create initialization scripts directory
      file: path={{ jenkins_home }}/init.groovy.d
        state=directory
        owner=jenkins
        group=jenkins
        mode=0775

    - name: Add initialization script to setup basic security
      template: src=./Jenkins/security.groovy.j2
        dest={{ jenkins_home }}/init.groovy.d/security.groovy

    - name: Turn off Jenkins setup wizard
      lineinfile:
        dest: /etc/init.d/jenkins
        regexp: '^JAVA_ARGS='
        line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
        insertbefore: '^DAEMON_ARGS='
      notify: restart jenkins

    - name: restart jenkins
      service: name=jenkins state=restarted

    - name: Retrieve Jenkins unlock code
      shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: jenkins_unlock
      notify:
        - restart jenkins

    - debug: msg="Jenkins unlock code (install admin password) is {{ jenkins_unlock.stdout }}"

  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted