version: '3'

services:
  api_with_json:
    restart: always
    build: ./api_with_json
    ports:
      - "5002:5000"
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=db

  api_without_json:
    restart: always
    build: ./api_without_json
    ports:
      - "5001:5000"
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=db

  statistics:
    restart: always
    build: ./statistics
    ports:
      - "5003:5000"
    env_file:
      - db.env
    environment:
      - POSTGRES_HOST=db

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - db.env

volumes:
  postgres_data:
