---
- name: Install Docker and Configure
  hosts: all
  become: true

  vars:
      source_file: ./ApiWithNginx
      destin_file: /opt/
      docker_apt_release_channel: stable
      docker_apt_arch: amd64
      docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
      docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      docker_compose_version: "1.24.0"

  tasks:
    - name: Update all apt packages
      apt:
        update_cache=yes
        force_apt_get=yes
        cache_valid_time=3600

    - name: Install packages using apt
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
          - default-jre
          - git
        state: present
        update_cache: no

    - name: Add Docker GPG apt Key
      apt_key:
        url: "{{ docker_apt_gpg_key }}"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "{{ docker_apt_repository }}"
        state: present
        update_cache: true

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: present
        update_cache: false

    - name: Modify privilege
      become: true
      shell: usermod -aG docker $USER

    - name: Change privilege of docker
      become: true
      file: dest=/usr/bin/docker mode=+x

    - name: Enabled docker service
      service:
          name: docker
          state: started
          enabled: yes

    - name: Install or upgrade docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 'a+x'
        force: yes
      when: >
        docker_compose_current_version is not defined
        or docker_compose_current_version is version(docker_compose_version, '<')

    - name: Clone repository
      command: git clone https://github.com/fm1ck3y/DevOpsProject /tmp/DevOpsProject

    - name: Move ApiWithNginx to /opt/
      command: mv -f /tmp/DevOpsProject/ApiWithNginx /opt/

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
